apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: liuk8s/telepresence:backend
        env:
        - name: APP_GREETING_NAME
          value: backend_minikube_deployment_yaml
        ports:
        - containerPort: 8080