apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31080
  selector:
    app: backend
    tier: backend